### ISSUE TITLE
mesa: build with no python mako

### ISSUE THREAD

**Issue by kyx0r** [ehawkvu/kiss-xorg#100]
I am worried, mesa is becoming more and more sus each day. Soon rust crap might get added. Any thoughts?

**Comment by wael444** [comment]
doesn't upstream kiss do the same?

**Comment by kyx0r** [comment]
> doesn't upstream kiss do the same?

They do, but I am not sure about rationale for doing so. Might need to see what its being used for. Im keeping old version for now.

**Comment by wael444** [comment]
```
~/mesa $ grep -R 'from mako' . | wc -l
67
```

**Comment by wael444** [comment]
Basically, i believe its required for 'Opcode' generation
