### ISSUE TITLE
outdated/updated packages

### ISSUE THREAD

**Issue by wael444** [ehawkvu/kiss-xorg#102]
@ehawkvu , shall we have a outdated tracker for packages that are not outdated; similar to KISS upstream?

unmaintained/outdated packages get dropped as well.

**Comment by ehawkvu** [comment]
I'm not opposed, but I'd like to have this be more automated. I've been looking for an excuse to use https://github.com/ehawkvu/kiss-personal/blob/master/bin/kiss-automail

**Comment by hovercats** [comment]
wouldnt that (more or less) make you the sole reciever of said emails @ehawkvu? :p
in regards to this repo anyway.

I can absolutly  see the benefit in community repo though.

**Comment by ehawkvu** [comment]
@hovercats `kiss-automail` can account for this, and if I were to use it, I would add two more files to the root of the directory, a blacklist for packages (ones that should not have emails sent out for whatever reason) and one for emails themselves. Naturally I'd blacklist myself from receiving emails.

As for the community repo, I think it'd be a pretty good solution, but I haven't really asked around.

**Comment by hovercats** [comment]
sounds good.

yeah, you should make an issue about it over at the upstream repo, or atleast mention it in the irc, if it hasnt already/
