### ISSUE TITLE
[discussion] useless packages

### ISSUE THREAD

**Issue by wael444** [ehawkvu/kiss-xorg#110]
the following packages have been considered useless due to having no recursal dependency in any package, i will be biased and mark packages that i deem 'useful'. but alot of packages here do not really have a purpose and the sole maintainer @ehawkvu, keeps these packages although i believe they should be removed for good.

- [X] `firefox`
- [X] `liberation-fonts`
- [X] `libva-utils`
- [X] `mpv`
- [X] `libXres`
- [X] `libXv`
- [X] `setxkbmap`
- [X] `sowm`
- [X] `tinyx`
- [ ] `twm`
- [X] `xcursorgen`
- [ ] `xdpyinfo`
- [X] `xev`
- [X] `xf86-input-libinput`
- [X] `xf86-video-amdgpu`
- [X] `xf86-video-ati`
- [X] `xf86-video-intel`
- [X] `xf86-video-nouveau`
- [X] `xf86-video-vesa`
- [ ] `xinit` - obsoleted by `sx`
- [X] `xinput`
- [X] `xrdb`
- [ ] `xrectsel` - obsoleted by `slop`
- [X] `xset`
- [X] `xsetroot`
- [X] `xwayland`
- [ ] `2bwm`
- [ ] `9wm`
- [ ] `abiword`
- [X] `alacritty`
- [ ] `alttab-git`
- [X] `apint`
- [ ] `autorandr`
- [X] `azpainter`
- [ ] `bdfedit`
- [ ] `berry`
- [ ] `brownout`
- [ ] `bspwm`
- [X] `chromium`
- [X] `ctwm`
- [X] `cwm`
- [ ] `dillo`  - obsoleted by a program midfavila probably made
- [X] `dmenu`
- [X] `dosbox`
- [ ] `doxygen`
- [X] `dragon-git` - should be renamed `dragon` though
- [X] `dwm`
- [ ] `dzen`
- [X] `emacs`
- [ ] `emacs-alpha`
- [ ] `emacs-git`
- [X] `farbfeld`
- [X] `feh`
- [X] `fontforge`
- [ ] `frankenwm`
- [X] `fvwm`
- [ ] `gettext-tiny`
- [X] `gimp`
- [X] `glmark2`
- [X] `gnuplot`
- [X] `godot`
- [ ] `grabc`
- [X] `graphviz` - whats the difference between this and `gnuplot`?
- [X] `herbe`
- [X] `herbstluftwm`
- [ ] `hexchat`
- [X] `hsetroot`
- [ ] `i3`
- [X] `inkscape`
- [ ] `irrlicht`
- [ ] `jansson`
- [X] `jwm`
- [X] `lemonbar`
- [X] `librewolf`
- [ ] `libsoup3` - should be renamed to `libsoup` after #24
- [ ] `libspectre`
- [ ] `libtasn1`
- [X] `lxappearance`
- [X] `maim`
- [ ] `meh`
- [X] `motif`
- [ ] `mplayer`
- [ ] `mypaint-brushes`
- [X] `netsurf-gtk3`
- [X] `nsxiv`
- [ ] `openscad`
- [ ] `otf2bdf`
- [ ] `palemoon`
- [X] `picom`
- [ ] `picom-git`
- [ ] `qt5-x11extras`
- [ ] `rxvt-unicode`
- [ ] `sasm`
- [ ] `schismtracker`
- [ ] `sct`
- [ ] `skippy-xd-git`
- [X] `slock`
- [ ] `slock-paranoid-git`
- [ ] `solvespace`
- [X] `spectrwm`
- [ ] `srain`
- [ ] `st-luke-git`
- [X] `stalonetray`
- [X] `stw`
- [X] `svkbd`
- [X] `sx`
- [X] `sxcs`
- [X] `sxhkd`
- [ ] `sxiv`
- [ ] `sylpheed`
- [X] `tabbed`
- [ ] `tinywm`
- [ ] `tkdiff`
- [ ] `vimb`
- [ ] `vimb-git`
- [X] `windowmaker`
- [ ] `winetricks`
- [ ] `wxWidgets`
- [X] `wyeb`
- [ ] `x11fs`
- [X] `x11vnc`
- [X] `xbanish`
- [X] `xclip`
- [X] `xcompmgr`
- [ ] `xdo`
- [X] `xdotool`
- [X] `xf86-video-fbdev`
- [X] `xf86-video-qxl`
- [X] `xf86-video-vmware`
- [X] `xfiles`
- [X] `xhost`
- [X] `xkill`
- [X] `xmenu`
- [ ] `xmodmap`
- [X] `xnotify`
- [ ] `xrandr-invert-colors`
- [X] `xsel`
- [ ] `xssstate`
- [X] `xwallpaper`
- [X] `xwm`
- [ ] `zircon`
- [ ] `zutty`

however, i have only did that list as a point of reference, as according to some packages in #109 , some are actually not used very commonly or i should say take up some space; this issue should be closed immediately if the repository maintainer disagrees with the removal of package abandonments.

i do believe certain packages SHOULD be removed Effective. such as `sxiv`, which is deprecated. there are probably other deprecated packages in this list as well.

**Comment by ehawkvu** [comment]
I don't think that removing 'useless' packages is the smartest move. I'm ok with removing completely, and actually deprecated packages like sxiv.

**Comment by wael444** [comment]
thanks for your comment, I have realized this due to the fact that most of the deprecated packages are maintained only by the literal repository creator, sorry for assuming. I had really only made this issue due to the oblivious amount of packages, as I had seen some that no longer have a use. Some packages are also old or deprecated, but one would need to go through all of them.
