### ISSUE TITLE
xf86-video-amdgpu: no cursor on 7900 XTX

### ISSUE THREAD

**Issue by davidgarland** [ehawkvu/kiss-xorg#121]
This is a known issue:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1894341.html
The above link mentions a patch for it:
https://cgit.freedesktop.org/xorg/driver/xf86-video-amdgpu/patch/?id=9c959fac3af28d191105f63236096ad456dca614

At the moment I'm just applying this patch in my custom repo and I [can confirm](https://codeberg.org/davidgarland/david-gkiss/src/branch/main/xorg/xf86-video-amdgpu) it fixes the issue, whereas doing SWCursor in my xorg.conf file leads to a flickering, stuttery cursor.

If a PR adding this patch would be accepted I'd be happy to submit one.

Another option that might work well (have not tested) is just using a more up-to-date source version (because the patch is in latest master) based on a fixed git commit rather than a packaged version; their stable releases for the package seem to come out pretty slowly. The last one was a year ago, and since then there have been 11 commits. You can find the commits at https://cgit.freedesktop.org/xorg/driver/xf86-video-amdgpu/log/

**Comment by ehawkvu** [comment]
I'd be happy to merge a PR that fixes xf86-video-amdgpu to this repo 👍
