### ISSUE TITLE
mpv won't launch with latest grepo libvpx

### ISSUE THREAD

**Issue by davidgarland** [ehawkvu/kiss-xorg#123]
```
bash-5.2$ mpv
mpv: error while loading shared libraries: libvpx.so.7: cannot open shared object file: No such file or directory
```
this happens even after doing `kiss b libvpx` followed by `kiss b mpv` to make sure both are up-to-date and built against each other.

**Comment by davidgarland** [comment]
Unsure who to complain to about this or what the best course of action is:
- Should the people maintaining `grepo` be asked to add a symlink `libvpx.so.8 -> libvpx.so.7`? Is that safe to do, in general?
- Should the people maintaining `mpv` be bugged about supporting libvpx.so.8?
- Is there anything that could be done in the `mpv` package here?

**Comment by apprehensions** [comment]
yeah i'm not exactly sure whats happening either, since rebuilding directly from git source, mpv links to `libvpx.so.7`, the only thing to do is to make a manual workaround aka symlink

**Comment by git-bruh** [comment]
You might have to rebuild ffmpeg aswell, the error likely stems from it since it's a transitive dependency. Though I did bump ffmpeg in grepo aswell

**Comment by apprehensions** [comment]
> You might have to rebuild ffmpeg aswell

fixes mpv, does not fix firefox
```
teapot$ firefox
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libvpx.so.7: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
*sigh* time to bruise my cpu

**Comment by ehawkvu** [comment]
> > You might have to rebuild ffmpeg aswell
> 
> fixes mpv, does not fix firefox
> 
> ```
> teapot$ firefox
> XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
> libvpx.so.7: cannot open shared object file: No such file or directory
> Couldn't load XPCOM.
> ```
> 
> i will wait for @ehawkvu to bump firefox to 110 instead.

bumped

**Comment by davidgarland** [comment]
does everything work on your end now @apprehensions?

if so this can be closed I think, as both firefox and mpv work for me following git-bruh's tip

**Comment by apprehensions** [comment]
yeah
