### ISSUE TITLE
ffmpeg won't build with vulkan present

### ISSUE THREAD

**Issue by davidgarland** [ehawkvu/kiss-xorg#127]
This is admittedly a problem that won't affect 99% of users since Vulkan isn't something widely packaged on KISS, but it is available via sewn's [gkiss-multilib](https://codeberg.org/sewn/gkiss-multilib) repo.

I found a thread [here](https://lists.openembedded.org/g/openembedded-core/topic/97218258?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3Arecentpostdate%2Fsticky%2C%2C%2C20%2C2%2C0%2C97218258) that describes the issue where they link [this patch](http://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff_plain/eb0455d64690) which deletes the offending lines. In the thread, they clarify that these features aren't yet used within ffmpeg (as of 25 Dec 2022) and that doing a patch to change the names to the proper ones seems like a bad idea from their POV.

I've [tried the patch myself](https://codeberg.org/davidgarland/david-gkiss/commit/48be8c725090a1406b8728bcd2b9d0562cff77de) and can confirm it works; if you'd be interested in me adding it here then I'd be happy to make a PR (and if not, I understand why). It's probably the case that some future version of ffmpeg will start to depend on these lines and get the identifiers' names right, at which point the patch could be removed.

Another much simpler option would be to just disable Vulkan support outright by just adding `--disable-vulkan` to the build config, which is what [it seems sewn did](https://codeberg.org/sewn/kiss-repo/commit/05998cf7b7c5fbf9c83c8812d02728c0259dc3b9). Then, likewise, we could just remove this flag when ffmpeg's Vulkan support is more mature.

**Comment by apprehensions** [comment]
Vulkan is not handled by kiss-xorg, and neither is there any Vulkan support on most applications. Why is the issue being made here? The only time i expected Vulkan working is when i was trying to run SuperTuxKart, as it ran with the more inferior OpenGL.
Who knows, maybe Vulkan will one time be pushed here and maintained by me???

**Comment by davidgarland** [comment]
> Why is the issue being made here?

Because it's an issue with ffmpeg, not with any other package. I mean, doing an override is possible (and is what I am doing, evidently, so this isn't a showstopper by any means) but it seems "nicer" to just have one package maintained that works for everyone. If practically no-one uses vulkan, and those who *do* use vulkan need it disabled on ffmpeg, then I think adding the `--disable-vulkan` option has no potential downsides.

OTOH *because* it's such a minor issue it's also perfectly fair to say it's not worth fixing and just drop the issue. I don't mind either way but just thought I'd bring this to light to attempt to reduce duplication of work.

**Comment by davidgarland** [comment]
I'll close this, as a solution through #128 will work in the future (somewhere in April, most likely)
