### ISSUE TITLE
build libX* libraries statically (in addition to shared)

### ISSUE THREAD

**Issue by ehawkvu** [ehawkvu/kiss-xorg#130]
Is there any interest in building the libraries under `xorg/` statically, in addition to shared? I know that there are quite a few
people using Xorg and a completely static kiss, so this should keep package forks to a minimum. 

Thoughts? @apprehensions @hovercats

**Comment by apprehensions** [comment]
I believe static linking should only be performed on *critical* applications such as BusyBox. it would be unnecessary to make the entire X11 suite (many libraries, as such.) completely statically linked. Aditionally most of the applications in the primary kiss community repositories (repo and community) are not even statically linked by itself.

Once upstream community decides to statically link most applications, then X can as well.

**Comment by ehawkvu** [comment]
@apprehensions This change would only be to the libraries - it would simply provide the static version of the library in addition to the shared version. This would allow you to then build some X apps statically if you wanted to, but would not be required.

**Comment by apprehensions** [comment]
ah ok well uhhh why not

**Comment by hovercats** [comment]
sounds good to me.
Ive already had to fork several of the xlibs, to enable static libs, so I can build some stuff statically linked. i.e. `tinyx`.

**Comment by ehawkvu** [comment]
implemented as of 6049118 - forgot to close the issue then
