### ISSUE TITLE
solve i3 bash dependency

### ISSUE THREAD

**Issue by apprehensions** [ehawkvu/kiss-xorg#131]
i asked this once and will again, **please drop/abandon packages that the MAINTAINER no longer uses**. AFAIK @ehawkvu uses dwm but is also the maintainer of i3 for example.

i3 requires bash at build time (but is not marked as a dependency). i attempted to solve this with a PR but lost interest with the maintainers as i3 is a pretty bad wm for the category of what kiss-xorg users are. ehawkvu (the maintainer of i3), please drop or abandon i3 if you no longer use it; or put them in the abandoned/ folder. or just solve the bash problem.

**Comment by ehawkvu** [comment]
i3 will now depend on bash

**Comment by apprehensions** [comment]
bruh
