### ISSUE TITLE
Chromium hardware accel

### ISSUE THREAD

**Issue by kyx0r** [ehawkvu/kiss-xorg#2]
Hello @ehawkvu 

This build of chromium is missing hardware accel. To fix adding 
```
for lib in libEGL.so libGLESv2.so; do
    install -Dm755 "out/Release/$lib" "$1/usr/lib/chromium"
done
```

in build script should fix the issue. This is only required for xorg, so on wayland it was removed.

**Comment by ehawkvu** [comment]
Thank you for noticing this! I just appended the lines to the chromium build script. If everything works as expected on a rebuild, feel free to close the issue!

**Comment by ehawkvu** [comment]
I just confirmed that hardware acceleration works, so I'm closing the issue.
