### ISSUE TITLE
Libsoup is out of date

### ISSUE THREAD

**Issue by hovercats** [ehawkvu/kiss-xorg#22]
As title says, libsoup is out of date.
Latest release is currently 3.0.4.
You may be aware of this already, but Im making an issue for it anyway, so
perhaps others can pitch in aswell.

Right of the bat, there are some issues, you guessed it, it doesnt build.

Here's the error:
`
[211/235] Linking target tests/request-body-test
ninja: job failed: cc  -o tests/ssl-test tests/ssl-test.p/ssl-test.c.o
-Wl,--as-needed -Wl,--no-undefined -O2 -pipe -march=znver1 -mtune=znver1
'-Wl,-rpath,$ORIGIN/:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-Wl,-rpath-link,/tmp/566/build/libsoup/output/tests -Wl,--start-group
tests/libtest-utils.so libsoup/libsoup-3.0-static.a /usr/lib/libglib-2.0.so
-Wl,--export-dynamic
/usr/lib/libgmodule-2.0.so -pthread /usr/lib/libgobject-2.0.so
/usr/lib/libgio-2.0.so /usr/lib/libgnutls.so /usr/lib/libsqlite3.so
/usr/lib/libpsl.so /usr/lib/libz.so /usr/lib/libnghttp2.so -Wl,--end-group
/usr/bin/ld: tests/ssl-test.p/ssl-test.c.o: in function `main':
/tmp/566/build/libsoup/output/../tests/ssl-test.c:717: undefined reference to
`gnutls_pkcs11_init'
/usr/bin/ld: /tmp/566/build/libsoup/output/../tests/ssl-test.c:718: undefined
reference to `gnutls_pkcs11_add_provider'
collect2: error: ld returned 1 exit status
ninja: subcommand failed
`

Fixing this is rather trivial, as I just disabled `pkcs11-tests`.
As Ive been doing some testing with this, I also managed to build libsoup 3.0.4
without disabling pkcs11-tests, but to do so, I had to build gnutls with
p11-kit.

edit: I had to clean up the post abit.
I also have issues with 3.0.4 not working with webkit2gtk, but Ill create a
separate issue for it.

**Comment by ehawkvu** [comment]
libsoup has been a tricky package. I've kept it on 2.74.2 since most packages don't complain about it. I've messed around with 3.0.4 and it was finicky. I have no problems with packaging libsoup 3.0.4 as libsoup3. I think carbs has done the same.

As for webkit, it's likely a configure option. From doing a basic grep of the files, I think you should be able to build with libsoup 3 just by changing `-DUSE_SOUP2=ON` to `-DUSE_SOUP2=OFF`.

I'll look into this more tomorrow.

**Comment by hovercats** [comment]
That may be the case, and it would perhaps be wise to separate them for those
packages thats explicitly problematic with 3.x. I too noticed, that 
Carbs linux did this, but its still in testing, so he's probably still 
ironing out some stuff.

I wasnt aware of the config flag, as I havent really looked into that part of
webkit too much, but in any case, I added the flag, and built webkit with
`-DUSE_SOUP2=OFF`, and webkit built successfully.
However, now surf, vimb, and wyeb will complain about `webkit2gtk-4.0` is
missing. This seems to be an issue with pkgconf not being able to find
`webkit2gtk-4.1.pc` and related files.
Ive tried to set `PKG_CONFIG_PATH`, but I havent had any luck in doing so
successfully.

I did some digging on surf's config.mk file, and changed 4.0 to 4.1, and surf
now builds. I did a quick test on vimb and wyeb aswell, and while the error
about webkit was gone, a whole lot of other errors took its place instead.
I dont currently use vimb/wyeb myself, but I wanted to test those aswell, to
see if the issue persisted across other webkit browsers too.

**Comment by ehawkvu** [comment]
Would it be wise then to add a check in webkit's build script for libsoup 3 and set the flag accordingly? 

Did you do testing of surf as well besides just the build? And I am a bit surprised about vimb and wyeb. Maybe it'd also be just changing a few lines in their Makfile?

Also if you want, feel free to make a PR for libsoup3, I'd be happy to merge. Otherwise I'll add it Monday.

**Comment by hovercats** [comment]
Yeah, I belive that would be a great idea.  Atleast untill we can iron out the cruft with the browsers atleast. Im not sure what else depends on libtool, but afaik, its ony the said browsers and webkit in this repo anyway. As for other repos, Id have to check when I get back on my laptop.

Ive used surf with libsoup3 for some hours now, and I havent had any appearany issues. So Surf seems to work fine with it.
They seem to need a little more work, but I havent gotten much past chaning the webkit version, but Ill look into that aswell.

Sounds good, Ill make one when I get back to the laptop, and once you merge, we can close  this issue aswell, and Ill make a new one for the browsers/webkit :D

**Comment by hovercats** [comment]
closing this, as #23 is now merged
