### ISSUE TITLE
webkit/-browsers to work with libsoup3

### ISSUE THREAD

**Issue by hovercats** [ehawkvu/kiss-xorg#24]
This has been discussed partially in #22.

but Ill give a rundown here anyway for details.

libsoup 3.x seems to give us issues with webkit2gtk, aswell as its browsers.
namely surf, vimb, and wyeb. (probably others aswell, but its those that exist
in this repo anyway)
All browsers will complain about `webkit2gtk-4.0` not existing, and to
adjust `PKG_CONFIG_PATH` accordingly. This however does not seem to work.
Atleast not to my ability to do so.
`Webkit2gtk` will complain similarly, except it will instead complain about
`libsoup` being missing altogether.

`
-- Could NOT find LibSoup: Found unsuitable version "", but required is at least
"2.54.0" (found LIBSOUP_INCLUDE_DIRS-NOTFOUND)
CMake Error at Source/cmake/OptionsGTK.cmake:210 (message):
  libsoup is required.
`

This error was easiliy fixed, as mentioned in #22, we just add
`-DUSE_SOUP2=OFF`, and webkit will build just fine.
This however did not solve webkit browsers issue with libsoup3.

As of now, Ive been able to solve this on `surf`.
in `config.mk` file we have to alter the following lines

`
GTKINC = `pkg-config --cflags gtk+-3.0 gcr-3 webkit2gtk-4.0`
GTKLIB = `pkg-config --libs gtk+-3.0 gcr-3 webkit2gtk-4.0`
WEBEXTINC = `pkg-config --cflags webkit2gtk-4.0 webkit2gtk-web-extension-4.0 gio-2.0`
WEBEXTLIBS = `pkg-config --libs webkit2gtk-4.0 webkit2gtk-web-extension-4.0 gio-2.0`
`
to
`
GTKINC = `pkg-config --cflags gtk+-3.0 gcr-3 webkit2gtk-4.1`
GTKLIB = `pkg-config --libs gtk+-3.0 gcr-3 webkit2gtk-4.1`
WEBEXTINC = `pkg-config --cflags webkit2gtk-4.1 webkit2gtk-web-extension-4.1 gio-2.0`
WEBEXTLIBS = `pkg-config --libs webkit2gtk-4.1 webkit2gtk-web-extension-4.1 gio-2.0`
`
Ive been using `surf` this way for several hours now, and there are no appearant
issues that ive noticed.

---

Now, on to `vimb`, and `wyeb`, they seem to be a different story altogether.

**wyeb**:
Doing the same as we've done with surf, will result in wyeb outputing this:
`
main.c: In function '_openuri':
main.c:1327:17: error: unknown type name 'SoupURI'
 1327 |                 SoupURI *suri = soup_uri_new(uri);
      |                 ^~~~~~~
ext.c: In function 'tofull':
ext.c:374:9: error: unknown type name 'SoupURI'
374  |         SoupURI *base = soup_uri_new(bases);
     |         ^~~~~~~
ext.c:375:9: error: unknown type name 'SoupURI'
375  |         SoupURI *full = soup_uri_new_with_base(base,uri);
     |         ^~~~~~~
   make: *** [makefile:14: wyeb] Error 1
   make: *** Waiting for unfinished jobs....
   ext.c: In function 'reqcb':
   ext.c:1827:9: error: unknown type name 'SoupURI'
1827 |         SoupURI *puri = soup_uri_new(pagestr);
     |         ^~~~~~~
ext.c:1841:17: error: unknown type name 'SoupURI'
1841 |                 SoupURI *ruri = soup_uri_new(reqstr);
     |                 ^~~~~~~
make: *** [makefile:22: ext.so] Error 1
`
Ive ran it with `CFLAGS=-w` to suppress the warnings, and to avoid contaminating
the output.
It does output some warnings about functions being wrong, but correcting them
comes out fruitless.

**vimb**:
vimb is more or less the story:
`
util.c: In function 'util_sanitize_uri':
util.c:806:5: error: unknown type name 'SoupURI'
  806 |     SoupURI *uri;
      |     ^~~~~~~
make[1]: *** [Makefile:43: util.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cc ext-util.lo
cc webext_main.so
make[2]: Leaving directory '/tmp/25200/build/vimb-git/src/webextension'
make[1]: Leaving directory '/tmp/25200/build/vimb-git/src'
make: *** [Makefile:57: src.subdir-all] Error 2
`
with vimb, we also have to add `webkit2gtk-web-extension-4.1` to the CFLAGS and 
LDFLAGS at the bottom of config.mk else itll complain about it being missing, 
on top of the other error.

as you mentioned in #22, it might be favorable to create a check for libsoup3 in
all of these packages, else some of them will ultimately fail if you use
libsoup3, or 2 for that matter, if webkit is build with `-DUSE_SOUP2=OFF`.
This is, once we figure out how to build all of them against libsoup3.

Ill be doing some more research on this, and return with my findings on the
subject.

**Comment by ehawkvu** [comment]
Just some initial stuff that I've found:

Apparently Webkit has 3 versions right now (as noted [here](https://github.com/johnfactotum/foliate/commit/8c00d67d57241bce965043fb98ba76782989eee5))

Those being:
4.0 -> Gtk3 & LibSoup2
4.1 -> Gtk3 & LibSoup3
5.0 -> Gtk4 & LibSoup3

Arch has also split up it's webkit pacakges to reflect this:

[webkit2gtk](https://archlinux.org/packages/extra/x86_64/webkit2gtk/)
[webkit2gtk-4.1](https://archlinux.org/packages/extra/x86_64/webkit2gtk-4.1/)
[webkit2gtk-5.0](https://archlinux.org/packages/extra/x86_64/webkit2gtk-5.0/)

Most, if not all of the WebKit based browsers depend on 4.0, with only epiphany depending on 4.1 (at least on Arch), and none depeding on 5.0.

It might require more than a simple change to PKG_CONFIG_PATH, and if we can get them to compile, we should send the patch upstream to each project.

**Comment by hovercats** [comment]
Nice find. So from what I could gather from all of this, aswell as what Ive found, 5.0 is utter useless at this point, and is to be avoided untill further developement has been done.
I looked into figuring out what differentiated 4.0 from 4.1, and from what I could gather, its wether or not libsoup3 is being used (correct me if Im wrong here).
As it seemed they use the same source. (As of now, 2.34.4)

It seems so indeed. Ill probably create an issue over at their github pages, and see if I cant get any respons to it, and Ill see if I cant hack together a bs solution to get it to build in the mean time.

**Comment by hovercats** [comment]
Issues has been created for (vimb)[https://github.com/fanglingsu/vimb/issues/7080], and (wyeb.)[https://github.com/jun7/wyeb/issues/49]

**Comment by hovercats** [comment]
Weyb has been resolved in a recent commit.
Which leaves only vimb left on our list.

**Comment by hovercats** [comment]
@ehawkvu `vimb` now has support for libsoup3 in a recent PR.

I can make a PR for the neccessary changes for the browsers. `wyeb` and `surf` is done deal, same is `vimb-git`. `vimb` would need a patch to have the libsoup3 changes.
would we favor a switch for this, or should we attempt to ditch the old libsoup2 alltogether?

Theres also 3 other packages that depend on `libsoup` pkg. (`appstream-glib`, `inkscape`, & `srain`) which would need looking into, if we wanna ditch libsoup2.

**Comment by hovercats** [comment]
fixed in #112. closing
