### ISSUE TITLE
Xorg no screens found

### ISSUE THREAD

**Issue by luis-07** [ehawkvu/kiss-xorg#25]
Hello, I'm not sure if this is the right place but my Xorg doesn't work. I installed dwm,xinit,xorg-server and xf86-video-amdgpu. I didn't load any kernel modules (except for ethernet drivers) because I don't know which I should load. when i type startx (as root and normal user) I get the error no screens found.

**Comment by ehawkvu** [comment]
Is your kernel configured correctly? If you are using a modern AMD gpu, you may need some of the firmware blobs from linux-firmware. For the new Ryzen laptop processors, I had to include this line:

```
CONFIG_EXTRA_FIRMWARE="amdgpu/renoir_asd.bin amdgpu/renoir_ce.bin amdgpu/renoir_dmcub.bin amdgpu/renoir_gpu_info.bin amdgpu/renoir_me.bin amdgpu/renoir_mec2.bin amdgpu/renoir_mec.bin amdgpu/renoir_pfp.bin amdgpu/renoir_rlc.bin amdgpu/renoir_sdma.bin amdgpu/renoir_ta.bin amdgpu/renoir_vcn.bin iwlwifi-cc-a0-46.ucode iwlwifi-cc-a0-59.ucode iwlwifi-cc-a0-53.ucode iwlwifi-cc-a0-62.ucode iwlwifi-cc-a0-55.ucode iwlwifi-cc-a0-48.ucode iwlwifi-cc-a0-50.ucode"
```

In my kernel config.

If it's not that, then it might have been an improper setting in the video section of the kernel config. 

Seems to be related: https://bbs.archlinux.org/viewtopic.php?id=205614 (intel graphics)

**Comment by luis-07** [comment]
I just rebooted and got a new error (see picture) and yes I have a Radeon laptop but I use the default gentoo kernel which works fine on gentoo but I don't have the package Linux-firmware installed. ![image](https://user-images.githubusercontent.com/69043370/153282595-c80b0ff1-68af-446b-a343-a1b6b797b624.jpeg)

**Comment by luis-07** [comment]
I think I'll just reinstall kiss because I have the feeling me digging into the system did break something and than I'll try to install Xorg again and come back if the error still comes up.

**Comment by ehawkvu** [comment]
Are you using libressl by chance? It also looks like you are running into errors with xorg-server itself.

**Comment by luis-07** [comment]
![image](https://user-images.githubusercontent.com/69043370/153432281-54b8475c-85cc-45cf-ba13-e1bcae8b749f.jpeg)
Reinstalling kiss and loading the amdgpu module fixed my problem but there are missing fonts I don't know how to install. When I run startx I can see dwm but my screen freezes, I can't switch tty's ... the only way to get back to a tty is to reboot.

**Comment by luis-07** [comment]
In the basil's of xorg-server you have to put the /usr in singe quotes

**Comment by ehawkvu** [comment]
I was only curious since the symbols that X was missing are from the system SSL library. And interesting. I haven't encountered that issue before with the xorg-server package. I'm glad you were able to find the fix for the issue, do you think it should be added to the package here?

**Comment by luis-07** [comment]
opened the pull request thanks for your help and the great work on this repo

**Comment by luis-07** [comment]
#26
