### ISSUE TITLE
Non root Xorg

### ISSUE THREAD

**Issue by luis-07** [ehawkvu/kiss-xorg#29]
I tried to start X as a normal user and I get an error message saying:
xauth /home/glenda/.serverauth.XXXX doas not exist. do I need elogind for an non root Xorg server? I already added my user to the video audio and tty group.

**Comment by ehawkvu** [comment]
Are you using `startx` or `sx`? You should not need elogind to start X as a non-root user. You may also want to enable either eudev, or mdevd through your init system.

If you are on running, try running(as root):
```
$ ln -s /etc/sv/mdevd /var/service
$ reboot
```

**Comment by luis-07** [comment]
Thanks ma this fixed my issue.

**Comment by luis-07** [comment]
It's incredible how much you know about Linux
