### ISSUE TITLE
gobject-introspection fails, as doctemplates file does not exist

### ISSUE THREAD

**Issue by hovercats** [ehawkvu/kiss-xorg#35]
Basically what the title says.

Meson outputs this:
```sh
giscanner/meson.build:58:0: ERROR: File doctemplates does not exist.
```

**Comment by eli-schwartz** [comment]
This was fixed in upstream gobject-introspection via https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/305

**Comment by hovercats** [comment]
So it seems.
In that case, we should be able to fetch the patch for it, so we dont have to wait for a new release.

**Comment by ehawkvu** [comment]
@hovercats gobject-introspection should build now, let me know if there are any issues with the package

@eli-schwartz Thank you for bringing this to my attention, as I was using meson 60, so I never encountered this issue.

**Comment by hovercats** [comment]
built just fine now it seems.
closing.
