### ISSUE TITLE
xkeyboard-config: regression with setxkbmap pkg

### ISSUE THREAD

**Issue by kyx0r** [ehawkvu/kiss-xorg#42]
when upgrading from 2.34 to 2.35 xkeyboard-config some path is broken and setxkbmap does not work anymore and errors withCouldn't find rules file (evdev)

**Comment by ehawkvu** [comment]
This should have been fixed as of #38. I know that a small [edit](https://github.com/ehawkvu/kiss-xorg/pull/38/files#diff-483c1c3782ce98f97378627771e66fb490c0298763b477c96c0bbfbf6af9a559R5) had to be made to the xml2lst script. 

I have encountered the same issue [before](https://github.com/ehawkvu/kiss-xorg/pull/32), so let me know if that fixes it for you.

**Comment by kyx0r** [comment]
Ok I see where the problem is. Thank you for you help in resolving this.
