### ISSUE TITLE
Compilation of gcc takes 4 hours

### ISSUE THREAD

**Issue by vaskark** [ehawkvu/kiss-xorg#43]
I recently started using this repo and the compilation of gcc itself is taking over 4 hours, compared to the main repo version which took about 40 minutes. Am I doing something wrong? This is in a VM, but still seems odd.

Make flags:

```
export CFLAGS="-O3 -pipe -march=native"
export CXXFLAGS="$CFLAGS"
export MAKEFLAGS="-j2"
```
Any advice would be greatly appreciated.
Thanks.

**Comment by ehawkvu** [comment]
That is really odd. I'm not aware of any software in this repo that would cause GCC to take that long. Do you have logs? And does GCC have any new dependencies after it's built?

**Comment by vaskark** [comment]
It is odd, isn't it? It took almost 6 hours last night. Ugh.
Unfortunately I only had logs turned on for compilation failures. But if I change it I'm going to have to go through the whole mess again.
I'll post it if I decide to go through this again.
Many thanks.

**Comment by ehawkvu** [comment]
Is it getting longer? Also what order are the repositories in your `KISS_PATH`? 

kiss should automatically store logs in `$HOME/.cache/kiss/logs` so it might be worth checking there.

**Comment by vaskark** [comment]
Yeah, it is getting longer.
These repos are placed ahead of the main ones, as per instructions.
Logs are set to only be created on compilation failure. Since it was successful there was no log file created. I did check in the expected folder.
Not sure what I'm going to do at this point. Might try the build again just to produce a log file to submit.
Thanks.

**Comment by ehawkvu** [comment]
Hmm. I'm honestly not sure what could be causing this, as none of the packages in this repo should interact in any way with the gcc package. Does disabling these repos fixes the issue or does the issue persist after disabling the repo?

**Comment by vaskark** [comment]
I'm not sure if that would affect anything at this point. The best thing might be to make a new VM from scratch (without this xorg repo) and see if gcc takes the same insane amount of time. Don't know when I'll get around to it, though.

**Comment by vaskark** [comment]
Here is the log for gcc 12.1 compile. It took about 6 hours.

[link](https://gist.github.com/vaskark/a7dbdf74d2bbe1670c28dc45a3c089c1)

**Comment by ehawkvu** [comment]
The gcc12 release also took a bit longer than usual for me too since it has to bootstrap itself. I haven't had a chance to give a good look at the logs yet.

**Comment by kyx0r** [comment]
Yes, I felt that too. I don't like it. Why does it need bootstrap when I already have 11.2 installed?
Is that too old for it now? Absurd. A good indication may be if they changed some configure options.
I will check the kiss size diff later, I have a feeling the package is a lot more bloated now.

**Comment by kyx0r** [comment]
Oh yes, gcc now has a lot more fat, 167MB VS 190MB
Look at the diff:
https://0x0.st/ouzy.txt

**Comment by kyx0r** [comment]
Ok definitely when compiling from gcc 12.1 to gcc 11.2 the time is around 16-18 minutes
and same is true vise versa.
timed:
3m 52.34s (gcc11 to compiling gcc 11)
18m 13.54s (gcc11 to compiling gcc 12)
4m 19.31s (gcc 12 compiling gcc 12)

As a one time thing I guess it's not super worrysome but best fix it if possible

**Comment by vaskark** [comment]
Not worrisome? Mine is taking 6 hours! I know it’s a VM and I only have 2 cores dedicated… but this is ridiculous.

**Comment by kyx0r** [comment]
Well, it's easy to say but not so easy to convince the maintainer. Anyways you just have to keep this in mind for gcc, you can comment out the check in the script.

**Comment by vaskark** [comment]
> Well, it's easy to say but not so easy to convince the maintainer. Anyways you just have to keep this in mind for gcc, you can comment out the check in the script.

Comment out the check in the script? Could you be more explicit? Kind of a noob at this.

**Comment by kyx0r** [comment]
https://0x0.st/oSiY.patch

apply it

**Comment by kyx0r** [comment]
@ehawkvu Close this issue?
