### ISSUE TITLE
palemoon: debugging symbols headacke

### ISSUE THREAD

**Issue by kyx0r** [ehawkvu/kiss-xorg#46]
Hi @ehawkvu I spent a day with existential crisis amidst trying to debug some browser crashes. 
The problem is that apparently even if you enable all the debug options in the mozconfig.in the package
will never install the executables and libraries with debug symbols (despite building them with -g)
Besides this, there is also KISS_STRIP which is an aditional step to cause accidental headacke. 
You can imagine making one mistake is 15 minutes wasted compiling, iteration time is not so great
(but it's better than anywhere else).

So when the package builds it creates the nonstripped binary in the objdir/dist/palemoon folder
and the libs are symlinked to where they are originally built.

I propose maybe to enchance our build script with some easier logic to enable debug install, maybe
set KISS_STRIP too. I haven't got around to implementing this yet, but how does this sound?

**Comment by ehawkvu** [comment]
Is there an easy way to enable this in the build script? Have you tested this out?

**Comment by kyx0r** [comment]
I have a custom package here, it's git version:
https://github.com/kyx0r/repo-main/tree/master/community/palemoon-git

Last time I tested it, it's horrible. open one tab and the cpu is 100% ALL the time. ver 29.4 doesn't have this problem

> Is there an easy way to enable this in the build script? Have you tested this out?
No idea, I lost my motivation to debug this nonsense for now.
ehawku, have a look here this is the issue I was having:
https://forum.palemoon.org/viewtopic.php?f=70&t=28244
