### ISSUE TITLE
caution: chromium 100.0.4896.60 crashes

### ISSUE THREAD

**Issue by kyx0r** [ehawkvu/kiss-xorg#49]
Howdy,

I get random:
```
[144284.716825] ThreadPoolForeg[1174]: segfault at 18 ip 00007f04cafe1c08 sp 00007f04c2d8f9c8 error 4 in libc.so[7f04caf7c000+7a000]
[144284.716862] Code: 00 00 40 f6 c7 07 48 89 f8 75 0f eb 1d 0f 1f 44 00 00 48 83 c0 01 a8 07 74
10 80 38 00 75 f3 48 29 f8 c3 0f 1f 80 00 00 00 00 <48> 8b 10 49 b8 ff fe fe fe fe fe fe fe 4a 8d 0c 02 48 f7 d2 48 21
[156838.474017] Chrome_IOThread[1479]: segfault at 1e00000000 ip 00007fab2118ef59 sp 00007fab177e9078 error 4 in libc.so[7fab2112a000+7a000]
[156838.474058] Code: 00 48 89 ca eb db 66 2e 0f 1f 84 00 00 00 00 00 90 48 85 d2 75 11 eb 21 90
48 83 c7 01 48 83 c6 01 48 83 ea 01 74 12 0f b6 06 <38> 07 74 eb 0f b6 07 0f b6 16 29 d0 c3 66 90 31 c0 c3 0f 1f 44 00
```

This completely crashes it. Usually when switching tabs or
even just hovering over the tabs. Though one time it crashed just
idle. Beware so you not waste your time.
I still have version 95 and it's stable. But to run older versions you
need ffmpeg 4.1, some older version of mesa and gcc 11. It's a pain.
Maybe in the future versions things will get better.

Self advetisement moment: currently testing version 97 + some custom fix
for gcc 12.1 hopefully no issues there.

**Comment by ehawkvu** [comment]
I get the same behavior too, I thought it was just my system. IIRC @git-bruh fixed this[1]? 

[1] https://github.com/kiss-community/community/pull/1011

**Comment by kyx0r** [comment]
I thought so too, but maybe it crashes now because of some other library that was updated.

For the meantime, I've built a special 97 version that works under ffmpeg 4.1 and newest mesa. 
However, with the newest mesa the gpu process exits out due to some error, but at least the
whole browser works. I had also to disable the swiftshader since the binary would error with undefined
symbols otherwise. Well this is still better than random crashes every 5 minutes.

[1] https://kyryl.tk/bin/chromium@97.0.4692.71-1.tar.gz
Package built with generic -O2, so should work on any cpu.

**Comment by kyx0r** [comment]
Actually, I take it back. On some hardware gpu still works even with the latest mesa. Intel works, amd doesn't.
This 97 package might be good for some thinkpad.

**Comment by kyx0r** [comment]
@ehawkvu How did you run chrome? I always run with --no-sandbox

**Comment by ehawkvu** [comment]
I don't use `--no-sandbox`, all my flags are [here](https://github.com/ehawkvu/dots/blob/master/shell/.config/shell/env.sh#L19).

**Comment by kyx0r** [comment]
Ok, just was doing something illiliti suggested. It makes no difference then.

**Comment by kyx0r** [comment]
> Actually, I take it back. On some hardware gpu still works even with the latest mesa. Intel works, amd doesn't. This 97 package might be good for some thinkpad.

Ok amdgpu does work, my mesa build was somehow broken

**Comment by ehawkvu** [comment]
@kyx0r any chance that you've tested the new 103 release? it seems to be more stable

**Comment by kyx0r** [comment]
Negative, haven't tested it. Maybe sometime this week. I use nextvfp (which is my custom version of fbff) and it relies on old ffmpeg api. So switching those deps for testing is quite inconvenient right now. If they fixed the bugs, great.

**Comment by kyx0r** [comment]
@ehawkvu Just finished building. Now testing for a few days if no problem found I close the issue.

For anybody else who wants to get the monster:
[1] https://kyryl.tk/bin/chromium@103.0.5060.53-1.tar.gz

**Comment by kyx0r** [comment]
@ehawkvu Okay I can finally migrate my repos to the up-to-date ffmpeg stack, it be easier for me to test future chrome versions

BTW, feel free to test the most based media player on linux:
[1] https://github.com/kyx0r/nextfvp

**Comment by kyx0r** [comment]
Can't confirm this, also I deleted all the chrome turds in ~/.config/chromium so maybe it's ok now, either way this issue needs rebranding so closing it for now.
