### ISSUE TITLE
KISS games?

### ISSUE THREAD

**Issue by kyx0r** [ehawkvu/kiss-xorg#56]
Yo,
there's a lot of good stuff here hidden in the depth's of git history:
https://github.com/sdsddsd1/kiss-games

kiss-games repo became a broken mess due to wayland switch and
stuff was deleted, lucklily I know where to look. Most of the games support
Xorg only and it's very unlikely any of them be updated with wayland.
I saw you package [xlennart-git](https://github.com/ehawkvu/kiss-xorg/tree/master/community/xlennart-git)
that's *in hilarious bro! Keep up good work with the repo, it's getting more popular XD.

If we were to adopt X11 games into this repo, does it deserve it's own folder? I think so.

**Comment by ehawkvu** [comment]
I'm on board with resurrecting some old packages, you may find my tools [kiss-tombstones](https://raw.githubusercontent.com/ehawkvu/kiss-personal/master/bin/kiss-tombstones) and [kiss-resurrect](https://raw.githubusercontent.com/ehawkvu/kiss-personal/master/bin/kiss-resurrect) to be useful. I think packaging them under `games/` is reasonable.

**Comment by ehawkvu** [comment]
Just moved all of the games that were under `community/` to `games/`

**Comment by kyx0r** [comment]
Cool, I'll add more games later ~

**Comment by wael444** [comment]
are some of these Xorg specific? because it'd be weird to have some games that aren't related or have support for Xorg

**Comment by kyx0r** [comment]
They are, because we specify xorg depends in this repo. Some of them may compile without libX11 for example and just run on framebuffer thanks to sdl2, but the build system will link to X11 by default if it finds it on the system.

**Comment by kyx0r** [comment]
Either way, kiss-games is dead so we just add and maintain our favorite games in this repo.
