### ISSUE TITLE
librewolf patch/compilation failure

### ISSUE THREAD

**Issue by wael444** [ehawkvu/kiss-xorg#57]
```
-> librewolf Building package (1/1)
-> librewolf Extracting sources
-> librewolf Starting build
patching file security/nss/lib/freebl/Makefile
patching file security/nss/lib/freebl/freebl.gyp
Hunk 1 FAILED 19/19.
       'conditions': [
         [ 'cc_is_clang==1', {
           'cflags': [
-            '-no-integrated-as',
           ],
           'cflags_mozilla': [
-            '-no-integrated-as',
           ],
           'asflags_mozilla': [
-            '-no-integrated-as',
           ],
         }],
       ],
patching file security/nss/lib/freebl/freebl_base.gypi
Hunk 1 FAILED 74/74.
           'conditions': [
             [ 'cc_is_clang==1 and fuzz!=1 and coverage!=1', {
               'cflags': [
-                '-no-integrated-as',
               ],
               'cflags_mozilla': [
-                '-no-integrated-as',
               ],
               'asflags_mozilla': [
-                '-no-integrated-as',
               ],
             }],
           ],
```
i think this is due to firefox 103.

**Comment by ehawkvu** [comment]
I'll see if I can bump it to 103

**Comment by ehawkvu** [comment]
It's been bumped, but not all of the librewolf patches are being applied (since they have to update them for 103). I'll gladly accept a PR re-enabling them however. 

I'm not sure why the patch failed to be applied, since it works fine on the regular firefox packages (regular and beta), and only has an issue on librewolf. Using GNU patch also fixed the issue.

**Comment by wael444** [comment]
> Using GNU patch also fixed the issue. 

interesting, i will try to make a PR for the patch.

**Comment by wael444** [comment]
wait, there is no direct patch in the librewolf kiss-xorg tree, is the patch provided by librewolf themselves?

**Comment by wael444** [comment]
it seems librewolf is compiling. i guess the patch was a problem upstream.
will close once it successfully 100% compiles and is usable
