### ISSUE TITLE
webkit2gtk: missing harfbuzz-icu

### ISSUE THREAD

**Issue by wael444** [ehawkvu/kiss-xorg#61]
related: https://github.com/ehawkvu/kiss-xorg/commit/2b9ea57c08d83d09d23f16405306dcefcdc067dd

but... harfbuzz-icu doesn't exist. well, not in this repo that i can find.

**Comment by kyx0r** [comment]
You need to add community repo to your KISS_PATH.

**Comment by kyx0r** [comment]
Nevermind, it's been dropped so kiiss-xorg should package all the deps here now.

**Comment by kyx0r** [comment]
My repo also dropped webkit, cause ruby no longer compiles with libressl and I don't care enough to make a patch, so I just wait for new release in hopes that they realize and fix it.

**Comment by wael444** [comment]
> it's been dropped so kiiss-xorg should package all the deps here now.

Why was it dropped?

**Comment by kyx0r** [comment]
git-bruh has no computer to test and maintain it I guess.

**Comment by wael444** [comment]
well, how else can i use webkit2gtk?
do i just open a PR here about the dropped package then?

**Comment by kyx0r** [comment]
Yes, you need to package it. As far as I can tell harf is only missing, glib-networking and libsoup is already packaged. Make pr on this repo, unless you want to maintain other packages what were dropped on /community

**Comment by wael444** [comment]
> If you want I can package it for you

As in making the build? i really appreciate your kindness! but that would mean YOU have to maintain it, i primarily want webkit2gtk just to try out the surf and wyeb browsers.

I am simply getting tired of Firefox.

> Or maybe it be more interesting for you to figure it out yourself? Working with git, forks and whatnot may be an interesting skill to learn. 

:D

**Comment by kyx0r** [comment]
Well, I think we have to add it since otherwise we be left with 3 useless broken packages.
Anyway, apparently I still have this package here:
https://github.com/kyx0r/repo-main/tree/master/community/harfbuzz-icu
or you can just checkout this git commit 87c4533b2bd228ce86484ddeffa4aa047a5a647e
on community/ ; compile and test the browsers you want .

side rant:
webkit was always unstable on musl, so expect random crashes and bugs.
That's another reason why I dropped it and don't use it nomore, besides the ruby crap.

**Comment by wael444** [comment]
what is the difference between harfbuzz-icu and harfbuzz by itself? and why is it needed for webkit2gtk anyway?

**Comment by wael444** [comment]
unfortunately libxslt is outdated and its maintainer is git-bruh, so i have to update it momentarily.

**Comment by wael444** [comment]
gnupg1
and openssh need to be installed prior to installing `gcr`. 

also now having this error:
```
Configuring gcr-viewer.desktop.in using configuration
Program msgfmt found: NO
```
well, gettext and msgfmt arent in repos it seems.

**Comment by wael444** [comment]
```
...
wael: testuser: building webkit2gtk
testuser: Don't
testuser: It's a waste of time
wael: but i wanna use surf
testuser: I've revisited it 20 times
testuser: Unusable
testuser: All webkit browsers
wael: aw well i guess i cant use wyeb or surf or webkit or luakit or anything webkit
wael: well now what im stuck with firefox
testuser: wael: You can use them but
testuser: Modern websites are too bloated for them
...
```

**Comment by kyx0r** [comment]
He's right. Basically for all modern web, chromium + vimium + ublock origin is where it's at. There's also palemoon, which i can't even compile past version 31+ and it's broken.

**Comment by kyx0r** [comment]
> what is the difference between harfbuzz-icu and harfbuzz by itself? and why is it needed for webkit2gtk anyway?

Pretty sure it's just bloat. Something to be done only to satisfy the build dependancy ICU.

**Comment by aabacchus** [comment]
> > what is the difference between harfbuzz-icu and harfbuzz by itself? and why is it needed for webkit2gtk anyway?
> 
> Pretty sure it's just bloat. Something to be done only to satisfy the build dependancy ICU.

Yeah, harfbuzz has an [awful] system of optionally linking the main libraries to ICU, graphite, freetype etc so you've got to rebuild it to add support.

**Comment by hovercats** [comment]
@ehawkvu what happened here really? I know you reverted 7238d494, but did you accedentally drop harfbuzz-icu at a later state?
in any case, how would you like to solve this? just readd it again?
or would you revisit making a switch like we attempted earlier?

**Comment by ehawkvu** [comment]
@hovercats I maintain harfbuzz-icu in kiss-tex, but if someone wants to add it to `community/` I'm not opposed.

**Comment by hovercats** [comment]
done. #70

**Comment by wael444** [comment]
just asking this again, is `harfbuzz-icu` still important? since `freetype-harfbuzz` simply requires a rebuild with `icu` installed for it to work.

**Comment by wael444** [comment]
really...

**Comment by wael444** [comment]
I mean, I thought it was more important
