### ISSUE TITLE
latest gcr version requires gettext

### ISSUE THREAD

**Issue by hovercats** [ehawkvu/kiss-xorg#65]
the latest version of gcr seems to require gettext, or specifically msgfmt (which is a part of gettext).
gcr is only needed by surf, so we could either patch out gcr (patch does exist).
or package gettext (or gettext-tiny). Im also sure we could patch out gettext aswell, but I havent looked into it.
gettext-tiny seems to be a makedep for gcr in any case.

**Comment by ehawkvu** [comment]
Sorry I haven't gotten to this sooner, I mean to. I can add gettext-tiny to the repo

**Comment by hovercats** [comment]
sounds good!

**Comment by hovercats** [comment]
fixed in 7d35a469
