### ISSUE TITLE
xorg-server: build fail (libxcvt)

### ISSUE THREAD

**Issue by kyx0r** [ehawkvu/kiss-xorg#77]
Idk maybe there is something wrong with my system, but following the muon transition for libxcvt I can't build it anymore.

https://0x0.st/ofHj.txt

**Comment by kyx0r** [comment]
I will be doing extensive testing now. I am back in action!

**Comment by kyx0r** [comment]
@ehawkvu Apparantly xorg has hard dependancy on libXdmcp. Evident by this build fail:

It should be added into depends.

[xdmcp](https://0x0.st/ofHJ.txt)

**Comment by kyx0r** [comment]
I confirm, the issue only occurs after the switch to muon.

**Comment by ehawkvu** [comment]
Fixed the issue with libxcvt.

**Comment by ehawkvu** [comment]
@kyx0r 
Try the following:
```
KISS_FORCE=1 kiss r libXdmcp
kiss b libxcb
kiss b xorg-server
```

**Comment by kyx0r** [comment]
> Fixed the issue with libxcvt.
Thank you.
Also, need to add libXdmcp as dep since it fails otherwise.

**Comment by kyx0r** [comment]
Looks like it works now. That's so strange. Why did it fail with libXdmcp missing and now it does not care about libXdmcp?
