### ISSUE TITLE
xwayland should be moved to extra/ or xorg/

### ISSUE THREAD

**Issue by wael444** [ehawkvu/kiss-xorg#89]
i have tested xwayland and i believe it should exit testing, and be put in either extra/ or xorg/.

it can also be safely switched out for muon for #86, and wayland users might want this package.

```
wael: does xwayland belong in community
wael: if at all
illiliti: no
wael: damn so it stays in kiss-xorg
```

**Comment by ehawkvu** [comment]
I'm glad someone has tested it - I havent had the time to. Was the setup roughly the same as on X? Were there any wayland specific things that you had to do? I'd definitely like to offer it as an option, so having some docs on how to set it up would be a first step IMO.

**Comment by wael444** [comment]
> Was the setup roughly the same as on X?

depends on the compositor, had to fork almost all of them just to have xwayland built in

> Were there any wayland specific things that you had to do?

many packages had to be built both FOR wayland and xorg

**Comment by ehawkvu** [comment]
> > Was the setup roughly the same as on X?
> 
> depends on the compositor, had to fork almost all of them just to have xwayland built in
> 
> > Were there any wayland specific things that you had to do?
> 
> many packages had to be built both FOR wayland and xorg

If you had to fork so many packages, would it make sense to ship these forked pkgs in their own repo, maybe `xwayland/`?

**Comment by wael444** [comment]
> If you had to fork so many packages, would it make sense to ship these forked pkgs in their own repo, maybe xwayland/?

No. i had to recompile so that programs can run Wayland natively.

### xwayland should have its own repository, yes; with all of the libraries baked in for Wayland users

and have a xwayland in xorg/ for people like me, who want to use both at the same time

**Comment by wael444** [comment]
i will start trying working on this.

**Comment by wael444** [comment]
i will NOT start working on this and suggest @ehawkvu to instead push the xwayland repository to `xorg`.

many propietary or X applications will still need X libraries. so a user is suggested to use the entire `xorg` repository as a benefit.

**Comment by wael444** [comment]
plz move it to xorg already

**Comment by ehawkvu** [comment]
done.

**Comment by wael444** [comment]
thx
