### ISSUE TITLE
gimp, inkscape, solvespace, rpcs3, openscad, citra-emu, srain: drop and use flatpak

### ISSUE THREAD

**Issue by wael444** [ehawkvu/kiss-xorg#93]
i know this issue might be trivial compared to #87 , but considering flatpak has many advantages such as sandboxing, less maintenance, less stress on the system, and is easier to manage i don't see why not.

KISS users often use Flatpaks for other big programs such as LibreOffice.

**Comment by ehawkvu** [comment]
Since I've already invested the effort in packaging them, I'm pretty averse to dropping these particular packages. Granted, we may be able to remove atk from the repo, but I think having native applications is preferable in almost all circumstances to flatpak. Just my 2 cents.

**Comment by wael444** [comment]
> but I think having native applications is preferable in almost all circumstances to flatpak.

Honestly, I thought the same. But considering the bloat that comes from this is insane.

**Comment by wael444** [comment]
> we may be able to remove atk from the repo

Personally, its quite a lot of work to remove atk and also patch them for muon as well.

**Comment by ehawkvu** [comment]
> > but I think having native applications is preferable in almost all circumstances to flatpak.
> 
> Honestly, I thought the same. But considering the bloat that comes from this is insane.

I don't consider 1 package to be that much bloat.

**Comment by wael444** [comment]
packages that rely on a dependency that is only required by it:
+ gimp
  + appstream-glib
  + gegl
  + gexiv2
  + gobject-introspection
  + libmypaint
  + poppler-data
+ inkscape
  + gc
  + gsl
  + potrace

+ openscad
  + cgal
  + eigen
  + libzip
  + opencsg
  + qscintilla-qt5
  + qt5-multimedia
+ srain
  + libsecret

+ packages that rely **ONLY** on the packages mentioned here
  + atkmm
  + glibmm
  + cairomm
  + pangomm
  + gtkmm3
  + gstreamer
  + gst-plugins-base
  + libsigc++

are you sure?

**Comment by wael444** [comment]
i still really suggest using the flatpak for these ngl..

**Comment by hovercats** [comment]
I actually have to agree with @ehawkvu here. Having native packages to me is favorable.
While I get that binary packages is infinitly more convinient than using a week to compile your complete system. This is still a source based distro, and I would expect to have to build packages from source.

Users are obviously free to use flatpak themselves and bypass all the hurdles of building i.e. rust, or chromium if they wish to.
I think that if users wishes to spend their time and effort to package packages like gimp, we should welcome it.
Its also been a thing for some KISS users to port things to kiss, just for the fun of it.. (maybe not do much anymore?)
Users have packaged xfce, kde and even pantheon just to name a few others.
And their effort should not be ignored imo.

**Comment by wael444** [comment]
yeah i have to agree native packages is quite nice
