### ISSUE TITLE
sylpheed: cannot build

### ISSUE THREAD

**Issue by apprehensions** [ehawkvu/kiss-xorg#98]
```
checking for GLIB - version >= 2.8.0... no
*** A new enough version of pkg-config was not found.
*** See http://www.freedesktop.org/software/pkgconfig/
configure: error: Test for GLib failed. See the 'INSTALL' for help.
```
https://codeberg.org/kiss-community/repo/src/branch/master/extra/glib/version
the upstreamed kiss glib package is 2.75.0.
@ehawkvu , do you still use this funky email client?

**Comment by ehawkvu** [comment]
I can build it just fine. I personally don't use the email client.

**Comment by wael444** [comment]
Then drop it ruthlessly. This is how KISS does it.

**Comment by apprehensions** [comment]
If you don't use sylpheed, why are you maintaining it?
